### ISSUE TITLE
Placeholders translation. 

### ISSUE THREAD

**Issue by umimehar** [tinoni/translate.js#10]
I was in need to translate the placeholder too. so i made this snippet of code. 

      for (var i = 0; i < $(".trn").get().length; i++) {
      if ($(".trn").get()[i].nodeName == "INPUT") {
        var placeholderValue = $($(".trn").get()[i]).attr("placeholder");

        var trn_key = $($(".trn").get()[i]).attr("data-trn-key");
        if (!trn_key) {
          trn_key = placeholderValue;
          $($(".trn").get()[i]).attr("data-trn-key", trn_key);   //store key for next time
        }
        $($(".trn").get()[i]).attr("placeholder", t[trn_key][settings.lang]);

      }
          
    }

**Comment by JeanPaiva42** [comment]
this.find(settings.css).each(function(i) {
      var $this = $(this);
      var trn_key = $this.attr("data-trn-key");
      if (!trn_key) {
        trn_key = $this.html();
        $this.attr("data-trn-key", trn_key);   //store key for next time
      }
      if($this.nodeName === 'INPUT'){
        var placeholderValue = $this.attr("placeholder");
        $this.attr("placeholder", that.get(placeholderValue));
      }
      $this.html(that.get(trn_key));
    });

**Comment by Calsy** [comment]
@JeanPaiva42 

```
if($this["0"].nodeName === 'INPUT'){
```

**Comment by umimehar** [comment]
https://github.com/umimehar/translateAll.jquery.js
i have created this fork for translate every thing on DOM :)
