### ISSUE TITLE
data-trn-key is overriding HTML text content

### ISSUE THREAD

**Issue by HOllarves** [tinoni/translate.js#7]
For some strange reason, the value of any data-trn-key will override the actual text in the HTML. I understand that data-trn-key is for paragraphs or long text, like some sort of a flag to quickly translate something. 

If I'm mistaken I'd love to know.

Thank you!

**Comment by jorgejeferson** [comment]
I do not quite understand your question, but come on.
The `trn` class is used to tell which `tag` will be translated.
I said ?!

**Comment by HOllarves** [comment]
@jorgejeferson Jorge, Now I understand.

I didn't know that when using data-trn-key I must provide translation for all the languages I'm using in my dictionary. That was causing my problem.

Thanks for the fast response, very much appreciated.

Gracias!
